/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AddSupervisur extends javax.swing.JFrame {

    /**
     * Creates new form AddSupervisur
     */
    public AddSupervisur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        textField9 = new java.awt.TextField();
        jButton2 = new javax.swing.JButton();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        label2.setBackground(new java.awt.Color(0, 0, 0));
        label2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Enter ID first :");
        getContentPane().add(label2);
        label2.setBounds(245, 65, 115, 28);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 106, 48, 17);

        textField9.setBackground(new java.awt.Color(0, 0, 0));
        textField9.setForeground(new java.awt.Color(255, 255, 255));
        textField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField9ActionPerformed(evt);
            }
        });
        getContentPane().add(textField9);
        textField9.setBounds(298, 103, 93, 20);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jButton2.setLabel("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 64, 67, 27);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(153, 0, 0));
        label3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        label3.setText("----------------------------------------------------------------------------");
        getContentPane().add(label3);
        label3.setBounds(0, 143, 762, 10);

        textField3.setBackground(new java.awt.Color(0, 0, 0));
        textField3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField3);
        textField3.setBounds(256, 182, 195, 20);

        textField2.setBackground(new java.awt.Color(0, 0, 0));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        getContentPane().add(textField2);
        textField2.setBounds(256, 225, 65, 20);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("subject");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(134, 182, 51, 17);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Academic Year");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(72, 225, 113, 17);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(323, 316, 127, 56);

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/app/pics/teach.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(900, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(900, 600));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField9ActionPerformed

    }//GEN-LAST:event_textField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int class_no;
        try{
            Teacher te=new Teacher();
            Connection con=te.getConnection();
            PreparedStatement sel;
            sel = con.prepareStatement("select * from teacher where Id_teacher=? ");
            sel.setInt(1, Integer.valueOf(textField9.getText()));
            ResultSet res=sel.executeQuery();
            if(res.next()){
              te.setId(Integer.valueOf(textField9.getText()));
             te.setName(res.getString(2));
               te.setAge(res.getInt(3));
                te.setSalary(res.getInt(5));
              te.setGraduation_Degree(res.getString(4));
               te.setGraduation_Year(res.getString(6));
                te.setYears_oF_Experince(res.getInt(7));
                	textField3.setText(res.getString(8));
                        te.setSudject_He_Teaches(textField3.getText());
               te.pass=res.getString(9);
               te.Supervisor="super";
               class_no=res.getInt(11);
               if(class_no==1)
               textField2.setText("1/1");
              else if(class_no==2)
               textField2.setText("2/1");
              else if(class_no==3)
               textField2.setText("1/2");
              else if(class_no==4)
               textField2.setText("2/2");
               te.setClass_no(class_no);
               te.SoperVisor();
            }
            else
            JOptionPane.showMessageDialog(null, "did not found it");
            sel.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Inserted");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          teacher__form tf=new teacher__form();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupervisur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupervisur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupervisur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupervisur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSupervisur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
