/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class EditTeacher extends javax.swing.JFrame {

String pass;
String sup;
String Super;
    /**
     * Creates new form EditTeacher
     */
    public EditTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField3 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textField5 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jLabel9 = new javax.swing.JLabel();
        textField6 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField9 = new java.awt.TextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ediit Teacher");
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        textField3.setBackground(new java.awt.Color(0, 0, 0));
        textField3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField3);
        textField3.setBounds(225, 118, 195, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 118, 48, 17);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 151, 48, 17);

        textField5.setBackground(new java.awt.Color(0, 0, 0));
        textField5.setForeground(new java.awt.Color(255, 255, 255));
        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        getContentPane().add(textField5);
        textField5.setBounds(225, 224, 195, 20);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Salary");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(29, 186, 48, 17);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Graduation_Degree");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 224, 128, 17);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/app/pics/ok.png"))); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 366, 120, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Graduation_Year");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 270, 119, 17);

        textField2.setBackground(new java.awt.Color(0, 0, 0));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField2);
        textField2.setBounds(225, 148, 65, 20);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Years_oF_Experince");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 300, 124, 20);

        textField6.setBackground(new java.awt.Color(0, 0, 0));
        textField6.setForeground(new java.awt.Color(255, 255, 255));
        textField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField6ActionPerformed(evt);
            }
        });
        getContentPane().add(textField6);
        textField6.setBounds(225, 186, 97, 20);

        textField7.setBackground(new java.awt.Color(0, 0, 0));
        textField7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField7);
        textField7.setBounds(225, 262, 128, 20);

        textField8.setBackground(new java.awt.Color(0, 0, 0));
        textField8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField8);
        textField8.setBounds(225, 297, 97, 20);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(35, 49, 48, 17);

        label2.setBackground(new java.awt.Color(0, 0, 0));
        label2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Enter ID first :");
        getContentPane().add(label2);
        label2.setBounds(24, 10, 115, 28);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(204, 255, 204));
        label3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        label3.setText("----------------------------------------------------------------------------");
        getContentPane().add(label3);
        label3.setBounds(10, 97, 427, 11);

        textField9.setBackground(new java.awt.Color(0, 0, 0));
        textField9.setForeground(new java.awt.Color(255, 255, 255));
        textField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField9ActionPerformed(evt);
            }
        });
        getContentPane().add(textField9);
        textField9.setBounds(224, 49, 93, 20);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jButton2.setLabel("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(336, 49, 111, 27);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Number of class he teaches");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 335, 190, 17);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(225, 335, 73, 20);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/app/pics/back.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 360, 120, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 0, 0);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/app/pics/teacher and student.png"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(900, 600));
        jLabel10.setMinimumSize(new java.awt.Dimension(900, 600));
        jLabel10.setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        Teacher te =new Teacher(Integer.valueOf(textField9.getText()),textField3.getText(),Integer.valueOf(textField2.getText()),textField5.getText(),Integer.valueOf(textField6.getText()),textField5.getText(),Integer.valueOf(textField7.getText()),sup);
te.pass=pass;
te.Supervisor=Super;
te.setClass_no(Integer.valueOf( jTextField1.getText()));
te.Edit();
JOptionPane.showMessageDialog(this, " Done ");
jTextField1.setText("");
textField2.setText("");
textField3.setText("");
textField5.setText("");
textField6.setText("");
textField7.setText("");
textField8.setText("");
textField9.setText("");

}
catch(Exception ex){
JOptionPane.showMessageDialog(this, " Did Not Done ");
}
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField6ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void jButton1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jButton1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1HierarchyChanged

    private void textField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField9ActionPerformed
        
       
    }//GEN-LAST:event_textField9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         try{
            Teacher te=new Teacher();
            Connection con=te.getConnection();
            PreparedStatement sel;
            sel = con.prepareStatement("select * from teacher where Id_teacher=? ");
            sel.setInt(1, Integer.valueOf(textField9.getText()));
            ResultSet res=sel.executeQuery();
            if(res.next()){
                textField3.setText(res.getString(2));
                textField2.setText(res.getString(3));
                textField6.setText(res.getString(5));
                textField5.setText(res.getString(4));
                textField7.setText(res.getString(6));
                textField8.setText(res.getString(7));
                sup=res.getString(8);
                pass=res.getString(9);
               Super=res.getString(10);
             jTextField1.setText(String.valueOf(res.getInt(11)));
            }
            else
            JOptionPane.showMessageDialog(null, "did not found it");
            sel.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Inserted");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,  ex.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        teacher__form tf=new teacher__form();
        tf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditTeacher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
